from .Adv_Loss import Adv_Loss
from .ComplEx_NNE_AER_Loss import ComplEx_NNE_AER_Loss
from .SimplE_Loss import SimplE_Loss
from .Cross_Entropy_Loss import Cross_Entropy_Loss
from .RGCN_Loss import RGCN_Loss
from .KBAT_Loss import KBAT_Loss
from .CrossE_Loss import CrossE_Loss
from .Margin_Loss import Margin_Loss
from .Sigmoid_Loss import Sigmoid_Loss
from .InfoNCE_Loss import InfoNCE_Loss
from .Cluster_Adv_Loss import Cluster_Adv_Loss
from .BCE_Loss import BCE_Loss
from .Adv_Bce_Loss import Adv_Bce_Loss
from .paper_loss import Paper_Loss